# Generated by Django 6.0 on 2026-03-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(choices=[('product', 'Canadian Product'), ('service', 'Service'), ('job', 'Job'), ('realestate', 'Real Estate')], max_length=100)),
                ('location', models.CharField(default='Canada', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(blank=True, default='https://picsum.photos/300/200?random=1')),
            ],
        ),
    ]
