# Generated by Django 6.0 on 2026-03-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_para', models.TextField(help_text='Short description shown on list cards')),
                ('features', models.JSONField(default=list, help_text='List of exactly 4 features (strings)')),
                ('image', models.URLField(blank=True, default='https://picsum.photos/800/400?random=10')),
                ('description_paras', models.JSONField(default=list, help_text="List of paragraphs/objects for the detail page. Example: ['Para 1 text', {'title': 'Subheading', 'text': 'content'}]")),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
