# Generated by Django 6.0 on 2026-03-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='features',
        ),
        migrations.AddField(
            model_name='service',
            name='feature1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='feature2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='feature3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='feature4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_paras',
            field=models.JSONField(blank=True, default=list, help_text='List of paragraphs. Example: ["Paragraph one", "Paragraph two"]'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='services/default.jpg', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_para',
            field=models.TextField(help_text='Short description for service cards'),
        ),
    ]
