# Generated by Django 6.0 on 2026-03-24 10:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_service_features_service_feature1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description_paras',
        ),
        migrations.AddField(
            model_name='service',
            name='detail_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Write full detailed content here with formatting', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_para',
            field=models.TextField(help_text='Short description shown on cards'),
        ),
    ]
