# Generated by Django 6.0 on 2026-03-24 11:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_service_description_paras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('consulting', 'Consulting'), ('marketing', 'Digital Marketing'), ('design', 'UI/UX Design'), ('immigration', 'Immigration Services'), ('other', 'Other')], max_length=100)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('short_description', models.TextField()),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('technologies', models.JSONField(blank=True, default=list, help_text='Example: ["React", "Django", "Tailwind"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
