# Generated by Django 6.0 on 2026-03-24 11:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.CharField(choices=[('business', 'Business & Consulting'), ('technology', 'Technology'), ('immigration', 'Immigration'), ('marketplace', 'Marketplace Tips'), ('canada', 'Canadian Life'), ('other', 'Other')], max_length=100)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title (recommended 50-60 chars)', max_length=250)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Description (150-160 chars)')),
                ('keywords', models.CharField(blank=True, help_text='Comma separated keywords', max_length=300)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (1200x630 recommended)', null=True, upload_to='blog/og/')),
                ('short_description', models.TextField(help_text='Used in cards and meta')),
                ('content', ckeditor.fields.RichTextField()),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='In minutes (auto-calculated if left 0)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
