# Generated by Django 6.0 on 2026-03-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_menuitem_delete_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Open in new tab'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='Leave empty for parent menu with dropdown', max_length=200),
        ),
    ]
